// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $create_index from "./routes/create/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $post_id_ from "./routes/post/[id].tsx";
import * as $search_index from "./routes/search/index.tsx";
import * as $LikeButton from "./islands/LikeButton.tsx";
import * as $MainView from "./islands/MainView.tsx";
import * as $PostCover from "./islands/PostCover.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/create/index.tsx": $create_index,
    "./routes/index.tsx": $index,
    "./routes/post/[id].tsx": $post_id_,
    "./routes/search/index.tsx": $search_index,
  },
  islands: {
    "./islands/LikeButton.tsx": $LikeButton,
    "./islands/MainView.tsx": $MainView,
    "./islands/PostCover.tsx": $PostCover,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
